/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh.beacon;  
@SuppressWarnings("all")
/** DataUseRequirementResource */
@org.apache.avro.specific.AvroGenerated
public class DataUseRequirementResource extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DataUseRequirementResource\",\"namespace\":\"org.ga4gh.beacon\",\"doc\":\"DataUseRequirementResource\",\"fields\":[{\"name\":\"name\",\"type\":\"string\",\"doc\":\"Data Use requirement\"},{\"name\":\"description\",\"type\":[\"null\",\"string\"],\"doc\":\"Description of Data Use requirement.\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** Data Use requirement */
   private java.lang.CharSequence name;
  /** Description of Data Use requirement. */
   private java.lang.CharSequence description;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public DataUseRequirementResource() {}

  /**
   * All-args constructor.
   */
  public DataUseRequirementResource(java.lang.CharSequence name, java.lang.CharSequence description) {
    this.name = name;
    this.description = description;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return description;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: description = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * Data Use requirement   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * Data Use requirement   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'description' field.
   * Description of Data Use requirement.   */
  public java.lang.CharSequence getDescription() {
    return description;
  }

  /**
   * Sets the value of the 'description' field.
   * Description of Data Use requirement.   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /** Creates a new DataUseRequirementResource RecordBuilder */
  public static org.ga4gh.beacon.DataUseRequirementResource.Builder newBuilder() {
    return new org.ga4gh.beacon.DataUseRequirementResource.Builder();
  }
  
  /** Creates a new DataUseRequirementResource RecordBuilder by copying an existing Builder */
  public static org.ga4gh.beacon.DataUseRequirementResource.Builder newBuilder(org.ga4gh.beacon.DataUseRequirementResource.Builder other) {
    return new org.ga4gh.beacon.DataUseRequirementResource.Builder(other);
  }
  
  /** Creates a new DataUseRequirementResource RecordBuilder by copying an existing DataUseRequirementResource instance */
  public static org.ga4gh.beacon.DataUseRequirementResource.Builder newBuilder(org.ga4gh.beacon.DataUseRequirementResource other) {
    return new org.ga4gh.beacon.DataUseRequirementResource.Builder(other);
  }
  
  /**
   * RecordBuilder for DataUseRequirementResource instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DataUseRequirementResource>
    implements org.apache.avro.data.RecordBuilder<DataUseRequirementResource> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence description;

    /** Creates a new Builder */
    private Builder() {
      super(org.ga4gh.beacon.DataUseRequirementResource.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ga4gh.beacon.DataUseRequirementResource.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing DataUseRequirementResource instance */
    private Builder(org.ga4gh.beacon.DataUseRequirementResource other) {
            super(org.ga4gh.beacon.DataUseRequirementResource.SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.description)) {
        this.description = data().deepCopy(fields()[1].schema(), other.description);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'name' field */
    public java.lang.CharSequence getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public org.ga4gh.beacon.DataUseRequirementResource.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'name' field */
    public org.ga4gh.beacon.DataUseRequirementResource.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'description' field */
    public java.lang.CharSequence getDescription() {
      return description;
    }
    
    /** Sets the value of the 'description' field */
    public org.ga4gh.beacon.DataUseRequirementResource.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.description = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'description' field has been set */
    public boolean hasDescription() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'description' field */
    public org.ga4gh.beacon.DataUseRequirementResource.Builder clearDescription() {
      description = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public DataUseRequirementResource build() {
      try {
        DataUseRequirementResource record = new DataUseRequirementResource();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.description = fieldSetFlags()[1] ? this.description : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
