/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh.methods;  
@SuppressWarnings("all")
/** This request maps to the body of `POST /referencesets/search`
as JSON. */
@org.apache.avro.specific.AvroGenerated
public class SearchReferenceSetsRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SearchReferenceSetsRequest\",\"namespace\":\"org.ga4gh.methods\",\"doc\":\"This request maps to the body of `POST /referencesets/search`\\nas JSON.\",\"fields\":[{\"name\":\"md5checksum\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"If not null, return the reference sets for which the\\n  `md5checksum` matches this string (case-sensitive, exact match).\\n  See `ReferenceSet::md5checksum` for details.\",\"default\":null},{\"name\":\"accession\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"If not null, return the reference sets for which the `accession`\\n  matches this string (case-sensitive, exact match).\",\"default\":null},{\"name\":\"assemblyId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"If not null, return the reference sets for which the `assemblyId`\\n  matches this string (case-sensitive, exact match).\",\"default\":null},{\"name\":\"pageSize\",\"type\":[\"null\",\"int\"],\"doc\":\"Specifies the maximum number of results to return in a single page.\\n  If unspecified, a system default will be used.\",\"default\":null},{\"name\":\"pageToken\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"The continuation token, which is used to page through large result sets.\\n  To get the next page of results, set this parameter to the value of\\n  `nextPageToken` from the previous response.\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** If not null, return the reference sets for which the
  `md5checksum` matches this string (case-sensitive, exact match).
  See `ReferenceSet::md5checksum` for details. */
   private java.lang.String md5checksum;
  /** If not null, return the reference sets for which the `accession`
  matches this string (case-sensitive, exact match). */
   private java.lang.String accession;
  /** If not null, return the reference sets for which the `assemblyId`
  matches this string (case-sensitive, exact match). */
   private java.lang.String assemblyId;
  /** Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used. */
   private java.lang.Integer pageSize;
  /** The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response. */
   private java.lang.String pageToken;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public SearchReferenceSetsRequest() {}

  /**
   * All-args constructor.
   */
  public SearchReferenceSetsRequest(java.lang.String md5checksum, java.lang.String accession, java.lang.String assemblyId, java.lang.Integer pageSize, java.lang.String pageToken) {
    this.md5checksum = md5checksum;
    this.accession = accession;
    this.assemblyId = assemblyId;
    this.pageSize = pageSize;
    this.pageToken = pageToken;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return md5checksum;
    case 1: return accession;
    case 2: return assemblyId;
    case 3: return pageSize;
    case 4: return pageToken;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: md5checksum = (java.lang.String)value$; break;
    case 1: accession = (java.lang.String)value$; break;
    case 2: assemblyId = (java.lang.String)value$; break;
    case 3: pageSize = (java.lang.Integer)value$; break;
    case 4: pageToken = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'md5checksum' field.
   * If not null, return the reference sets for which the
  `md5checksum` matches this string (case-sensitive, exact match).
  See `ReferenceSet::md5checksum` for details.   */
  public java.lang.String getMd5checksum() {
    return md5checksum;
  }

  /**
   * Sets the value of the 'md5checksum' field.
   * If not null, return the reference sets for which the
  `md5checksum` matches this string (case-sensitive, exact match).
  See `ReferenceSet::md5checksum` for details.   * @param value the value to set.
   */
  public void setMd5checksum(java.lang.String value) {
    this.md5checksum = value;
  }

  /**
   * Gets the value of the 'accession' field.
   * If not null, return the reference sets for which the `accession`
  matches this string (case-sensitive, exact match).   */
  public java.lang.String getAccession() {
    return accession;
  }

  /**
   * Sets the value of the 'accession' field.
   * If not null, return the reference sets for which the `accession`
  matches this string (case-sensitive, exact match).   * @param value the value to set.
   */
  public void setAccession(java.lang.String value) {
    this.accession = value;
  }

  /**
   * Gets the value of the 'assemblyId' field.
   * If not null, return the reference sets for which the `assemblyId`
  matches this string (case-sensitive, exact match).   */
  public java.lang.String getAssemblyId() {
    return assemblyId;
  }

  /**
   * Sets the value of the 'assemblyId' field.
   * If not null, return the reference sets for which the `assemblyId`
  matches this string (case-sensitive, exact match).   * @param value the value to set.
   */
  public void setAssemblyId(java.lang.String value) {
    this.assemblyId = value;
  }

  /**
   * Gets the value of the 'pageSize' field.
   * Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used.   */
  public java.lang.Integer getPageSize() {
    return pageSize;
  }

  /**
   * Sets the value of the 'pageSize' field.
   * Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used.   * @param value the value to set.
   */
  public void setPageSize(java.lang.Integer value) {
    this.pageSize = value;
  }

  /**
   * Gets the value of the 'pageToken' field.
   * The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response.   */
  public java.lang.String getPageToken() {
    return pageToken;
  }

  /**
   * Sets the value of the 'pageToken' field.
   * The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response.   * @param value the value to set.
   */
  public void setPageToken(java.lang.String value) {
    this.pageToken = value;
  }

  /** Creates a new SearchReferenceSetsRequest RecordBuilder */
  public static org.ga4gh.methods.SearchReferenceSetsRequest.Builder newBuilder() {
    return new org.ga4gh.methods.SearchReferenceSetsRequest.Builder();
  }
  
  /** Creates a new SearchReferenceSetsRequest RecordBuilder by copying an existing Builder */
  public static org.ga4gh.methods.SearchReferenceSetsRequest.Builder newBuilder(org.ga4gh.methods.SearchReferenceSetsRequest.Builder other) {
    return new org.ga4gh.methods.SearchReferenceSetsRequest.Builder(other);
  }
  
  /** Creates a new SearchReferenceSetsRequest RecordBuilder by copying an existing SearchReferenceSetsRequest instance */
  public static org.ga4gh.methods.SearchReferenceSetsRequest.Builder newBuilder(org.ga4gh.methods.SearchReferenceSetsRequest other) {
    return new org.ga4gh.methods.SearchReferenceSetsRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for SearchReferenceSetsRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SearchReferenceSetsRequest>
    implements org.apache.avro.data.RecordBuilder<SearchReferenceSetsRequest> {

    private java.lang.String md5checksum;
    private java.lang.String accession;
    private java.lang.String assemblyId;
    private java.lang.Integer pageSize;
    private java.lang.String pageToken;

    /** Creates a new Builder */
    private Builder() {
      super(org.ga4gh.methods.SearchReferenceSetsRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ga4gh.methods.SearchReferenceSetsRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.md5checksum)) {
        this.md5checksum = data().deepCopy(fields()[0].schema(), other.md5checksum);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accession)) {
        this.accession = data().deepCopy(fields()[1].schema(), other.accession);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.assemblyId)) {
        this.assemblyId = data().deepCopy(fields()[2].schema(), other.assemblyId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pageSize)) {
        this.pageSize = data().deepCopy(fields()[3].schema(), other.pageSize);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pageToken)) {
        this.pageToken = data().deepCopy(fields()[4].schema(), other.pageToken);
        fieldSetFlags()[4] = true;
      }
    }
    
    /** Creates a Builder by copying an existing SearchReferenceSetsRequest instance */
    private Builder(org.ga4gh.methods.SearchReferenceSetsRequest other) {
            super(org.ga4gh.methods.SearchReferenceSetsRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.md5checksum)) {
        this.md5checksum = data().deepCopy(fields()[0].schema(), other.md5checksum);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.accession)) {
        this.accession = data().deepCopy(fields()[1].schema(), other.accession);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.assemblyId)) {
        this.assemblyId = data().deepCopy(fields()[2].schema(), other.assemblyId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pageSize)) {
        this.pageSize = data().deepCopy(fields()[3].schema(), other.pageSize);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.pageToken)) {
        this.pageToken = data().deepCopy(fields()[4].schema(), other.pageToken);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'md5checksum' field */
    public java.lang.String getMd5checksum() {
      return md5checksum;
    }
    
    /** Sets the value of the 'md5checksum' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder setMd5checksum(java.lang.String value) {
      validate(fields()[0], value);
      this.md5checksum = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'md5checksum' field has been set */
    public boolean hasMd5checksum() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'md5checksum' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder clearMd5checksum() {
      md5checksum = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'accession' field */
    public java.lang.String getAccession() {
      return accession;
    }
    
    /** Sets the value of the 'accession' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder setAccession(java.lang.String value) {
      validate(fields()[1], value);
      this.accession = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'accession' field has been set */
    public boolean hasAccession() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'accession' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder clearAccession() {
      accession = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'assemblyId' field */
    public java.lang.String getAssemblyId() {
      return assemblyId;
    }
    
    /** Sets the value of the 'assemblyId' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder setAssemblyId(java.lang.String value) {
      validate(fields()[2], value);
      this.assemblyId = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'assemblyId' field has been set */
    public boolean hasAssemblyId() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'assemblyId' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder clearAssemblyId() {
      assemblyId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'pageSize' field */
    public java.lang.Integer getPageSize() {
      return pageSize;
    }
    
    /** Sets the value of the 'pageSize' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder setPageSize(java.lang.Integer value) {
      validate(fields()[3], value);
      this.pageSize = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'pageSize' field has been set */
    public boolean hasPageSize() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'pageSize' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder clearPageSize() {
      pageSize = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'pageToken' field */
    public java.lang.String getPageToken() {
      return pageToken;
    }
    
    /** Sets the value of the 'pageToken' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder setPageToken(java.lang.String value) {
      validate(fields()[4], value);
      this.pageToken = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'pageToken' field has been set */
    public boolean hasPageToken() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'pageToken' field */
    public org.ga4gh.methods.SearchReferenceSetsRequest.Builder clearPageToken() {
      pageToken = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public SearchReferenceSetsRequest build() {
      try {
        SearchReferenceSetsRequest record = new SearchReferenceSetsRequest();
        record.md5checksum = fieldSetFlags()[0] ? this.md5checksum : (java.lang.String) defaultValue(fields()[0]);
        record.accession = fieldSetFlags()[1] ? this.accession : (java.lang.String) defaultValue(fields()[1]);
        record.assemblyId = fieldSetFlags()[2] ? this.assemblyId : (java.lang.String) defaultValue(fields()[2]);
        record.pageSize = fieldSetFlags()[3] ? this.pageSize : (java.lang.Integer) defaultValue(fields()[3]);
        record.pageToken = fieldSetFlags()[4] ? this.pageToken : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
