/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh.methods;  
@SuppressWarnings("all")
/** This request maps to the body of `POST /variants/search` as JSON. */
@org.apache.avro.specific.AvroGenerated
public class SearchVariantsRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SearchVariantsRequest\",\"namespace\":\"org.ga4gh.methods\",\"doc\":\"This request maps to the body of `POST /variants/search` as JSON.\",\"fields\":[{\"name\":\"variantSetId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The `VariantSet` to search.\"},{\"name\":\"callSetIds\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}],\"doc\":\"Only return variant calls which belong to call sets with these IDs.\\n  If an empty array, returns variants without any call objects.\\n  If null, returns all variant calls.\",\"default\":null},{\"name\":\"referenceName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Required. Only return variants on this reference.\"},{\"name\":\"start\",\"type\":\"long\",\"doc\":\"Required. The beginning of the window (0-based, inclusive) for\\n  which overlapping variants should be returned.\\n  Genomic positions are non-negative integers less than reference length.\\n  Requests spanning the join of circular genomes are represented as\\n  two requests one on each side of the join (position 0).\"},{\"name\":\"end\",\"type\":\"long\",\"doc\":\"Required. The end of the window (0-based, exclusive) for which overlapping\\n  variants should be returned.\"},{\"name\":\"pageSize\",\"type\":[\"null\",\"int\"],\"doc\":\"Specifies the maximum number of results to return in a single page.\\n  If unspecified, a system default will be used.\",\"default\":null},{\"name\":\"pageToken\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"The continuation token, which is used to page through large result sets.\\n  To get the next page of results, set this parameter to the value of\\n  `nextPageToken` from the previous response.\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The `VariantSet` to search. */
   private java.lang.String variantSetId;
  /** Only return variant calls which belong to call sets with these IDs.
  If an empty array, returns variants without any call objects.
  If null, returns all variant calls. */
   private java.util.List<java.lang.String> callSetIds;
  /** Required. Only return variants on this reference. */
   private java.lang.String referenceName;
  /** Required. The beginning of the window (0-based, inclusive) for
  which overlapping variants should be returned.
  Genomic positions are non-negative integers less than reference length.
  Requests spanning the join of circular genomes are represented as
  two requests one on each side of the join (position 0). */
   private long start;
  /** Required. The end of the window (0-based, exclusive) for which overlapping
  variants should be returned. */
   private long end;
  /** Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used. */
   private java.lang.Integer pageSize;
  /** The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response. */
   private java.lang.String pageToken;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public SearchVariantsRequest() {}

  /**
   * All-args constructor.
   */
  public SearchVariantsRequest(java.lang.String variantSetId, java.util.List<java.lang.String> callSetIds, java.lang.String referenceName, java.lang.Long start, java.lang.Long end, java.lang.Integer pageSize, java.lang.String pageToken) {
    this.variantSetId = variantSetId;
    this.callSetIds = callSetIds;
    this.referenceName = referenceName;
    this.start = start;
    this.end = end;
    this.pageSize = pageSize;
    this.pageToken = pageToken;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return variantSetId;
    case 1: return callSetIds;
    case 2: return referenceName;
    case 3: return start;
    case 4: return end;
    case 5: return pageSize;
    case 6: return pageToken;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: variantSetId = (java.lang.String)value$; break;
    case 1: callSetIds = (java.util.List<java.lang.String>)value$; break;
    case 2: referenceName = (java.lang.String)value$; break;
    case 3: start = (java.lang.Long)value$; break;
    case 4: end = (java.lang.Long)value$; break;
    case 5: pageSize = (java.lang.Integer)value$; break;
    case 6: pageToken = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'variantSetId' field.
   * The `VariantSet` to search.   */
  public java.lang.String getVariantSetId() {
    return variantSetId;
  }

  /**
   * Sets the value of the 'variantSetId' field.
   * The `VariantSet` to search.   * @param value the value to set.
   */
  public void setVariantSetId(java.lang.String value) {
    this.variantSetId = value;
  }

  /**
   * Gets the value of the 'callSetIds' field.
   * Only return variant calls which belong to call sets with these IDs.
  If an empty array, returns variants without any call objects.
  If null, returns all variant calls.   */
  public java.util.List<java.lang.String> getCallSetIds() {
    return callSetIds;
  }

  /**
   * Sets the value of the 'callSetIds' field.
   * Only return variant calls which belong to call sets with these IDs.
  If an empty array, returns variants without any call objects.
  If null, returns all variant calls.   * @param value the value to set.
   */
  public void setCallSetIds(java.util.List<java.lang.String> value) {
    this.callSetIds = value;
  }

  /**
   * Gets the value of the 'referenceName' field.
   * Required. Only return variants on this reference.   */
  public java.lang.String getReferenceName() {
    return referenceName;
  }

  /**
   * Sets the value of the 'referenceName' field.
   * Required. Only return variants on this reference.   * @param value the value to set.
   */
  public void setReferenceName(java.lang.String value) {
    this.referenceName = value;
  }

  /**
   * Gets the value of the 'start' field.
   * Required. The beginning of the window (0-based, inclusive) for
  which overlapping variants should be returned.
  Genomic positions are non-negative integers less than reference length.
  Requests spanning the join of circular genomes are represented as
  two requests one on each side of the join (position 0).   */
  public java.lang.Long getStart() {
    return start;
  }

  /**
   * Sets the value of the 'start' field.
   * Required. The beginning of the window (0-based, inclusive) for
  which overlapping variants should be returned.
  Genomic positions are non-negative integers less than reference length.
  Requests spanning the join of circular genomes are represented as
  two requests one on each side of the join (position 0).   * @param value the value to set.
   */
  public void setStart(java.lang.Long value) {
    this.start = value;
  }

  /**
   * Gets the value of the 'end' field.
   * Required. The end of the window (0-based, exclusive) for which overlapping
  variants should be returned.   */
  public java.lang.Long getEnd() {
    return end;
  }

  /**
   * Sets the value of the 'end' field.
   * Required. The end of the window (0-based, exclusive) for which overlapping
  variants should be returned.   * @param value the value to set.
   */
  public void setEnd(java.lang.Long value) {
    this.end = value;
  }

  /**
   * Gets the value of the 'pageSize' field.
   * Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used.   */
  public java.lang.Integer getPageSize() {
    return pageSize;
  }

  /**
   * Sets the value of the 'pageSize' field.
   * Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used.   * @param value the value to set.
   */
  public void setPageSize(java.lang.Integer value) {
    this.pageSize = value;
  }

  /**
   * Gets the value of the 'pageToken' field.
   * The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response.   */
  public java.lang.String getPageToken() {
    return pageToken;
  }

  /**
   * Sets the value of the 'pageToken' field.
   * The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response.   * @param value the value to set.
   */
  public void setPageToken(java.lang.String value) {
    this.pageToken = value;
  }

  /** Creates a new SearchVariantsRequest RecordBuilder */
  public static org.ga4gh.methods.SearchVariantsRequest.Builder newBuilder() {
    return new org.ga4gh.methods.SearchVariantsRequest.Builder();
  }
  
  /** Creates a new SearchVariantsRequest RecordBuilder by copying an existing Builder */
  public static org.ga4gh.methods.SearchVariantsRequest.Builder newBuilder(org.ga4gh.methods.SearchVariantsRequest.Builder other) {
    return new org.ga4gh.methods.SearchVariantsRequest.Builder(other);
  }
  
  /** Creates a new SearchVariantsRequest RecordBuilder by copying an existing SearchVariantsRequest instance */
  public static org.ga4gh.methods.SearchVariantsRequest.Builder newBuilder(org.ga4gh.methods.SearchVariantsRequest other) {
    return new org.ga4gh.methods.SearchVariantsRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for SearchVariantsRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SearchVariantsRequest>
    implements org.apache.avro.data.RecordBuilder<SearchVariantsRequest> {

    private java.lang.String variantSetId;
    private java.util.List<java.lang.String> callSetIds;
    private java.lang.String referenceName;
    private long start;
    private long end;
    private java.lang.Integer pageSize;
    private java.lang.String pageToken;

    /** Creates a new Builder */
    private Builder() {
      super(org.ga4gh.methods.SearchVariantsRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ga4gh.methods.SearchVariantsRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.variantSetId)) {
        this.variantSetId = data().deepCopy(fields()[0].schema(), other.variantSetId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.callSetIds)) {
        this.callSetIds = data().deepCopy(fields()[1].schema(), other.callSetIds);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.referenceName)) {
        this.referenceName = data().deepCopy(fields()[2].schema(), other.referenceName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.start)) {
        this.start = data().deepCopy(fields()[3].schema(), other.start);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.end)) {
        this.end = data().deepCopy(fields()[4].schema(), other.end);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.pageSize)) {
        this.pageSize = data().deepCopy(fields()[5].schema(), other.pageSize);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.pageToken)) {
        this.pageToken = data().deepCopy(fields()[6].schema(), other.pageToken);
        fieldSetFlags()[6] = true;
      }
    }
    
    /** Creates a Builder by copying an existing SearchVariantsRequest instance */
    private Builder(org.ga4gh.methods.SearchVariantsRequest other) {
            super(org.ga4gh.methods.SearchVariantsRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.variantSetId)) {
        this.variantSetId = data().deepCopy(fields()[0].schema(), other.variantSetId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.callSetIds)) {
        this.callSetIds = data().deepCopy(fields()[1].schema(), other.callSetIds);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.referenceName)) {
        this.referenceName = data().deepCopy(fields()[2].schema(), other.referenceName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.start)) {
        this.start = data().deepCopy(fields()[3].schema(), other.start);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.end)) {
        this.end = data().deepCopy(fields()[4].schema(), other.end);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.pageSize)) {
        this.pageSize = data().deepCopy(fields()[5].schema(), other.pageSize);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.pageToken)) {
        this.pageToken = data().deepCopy(fields()[6].schema(), other.pageToken);
        fieldSetFlags()[6] = true;
      }
    }

    /** Gets the value of the 'variantSetId' field */
    public java.lang.String getVariantSetId() {
      return variantSetId;
    }
    
    /** Sets the value of the 'variantSetId' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder setVariantSetId(java.lang.String value) {
      validate(fields()[0], value);
      this.variantSetId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'variantSetId' field has been set */
    public boolean hasVariantSetId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'variantSetId' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder clearVariantSetId() {
      variantSetId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'callSetIds' field */
    public java.util.List<java.lang.String> getCallSetIds() {
      return callSetIds;
    }
    
    /** Sets the value of the 'callSetIds' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder setCallSetIds(java.util.List<java.lang.String> value) {
      validate(fields()[1], value);
      this.callSetIds = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'callSetIds' field has been set */
    public boolean hasCallSetIds() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'callSetIds' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder clearCallSetIds() {
      callSetIds = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'referenceName' field */
    public java.lang.String getReferenceName() {
      return referenceName;
    }
    
    /** Sets the value of the 'referenceName' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder setReferenceName(java.lang.String value) {
      validate(fields()[2], value);
      this.referenceName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'referenceName' field has been set */
    public boolean hasReferenceName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'referenceName' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder clearReferenceName() {
      referenceName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'start' field */
    public java.lang.Long getStart() {
      return start;
    }
    
    /** Sets the value of the 'start' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder setStart(long value) {
      validate(fields()[3], value);
      this.start = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'start' field has been set */
    public boolean hasStart() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'start' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder clearStart() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'end' field */
    public java.lang.Long getEnd() {
      return end;
    }
    
    /** Sets the value of the 'end' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder setEnd(long value) {
      validate(fields()[4], value);
      this.end = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'end' field has been set */
    public boolean hasEnd() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'end' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder clearEnd() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'pageSize' field */
    public java.lang.Integer getPageSize() {
      return pageSize;
    }
    
    /** Sets the value of the 'pageSize' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder setPageSize(java.lang.Integer value) {
      validate(fields()[5], value);
      this.pageSize = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'pageSize' field has been set */
    public boolean hasPageSize() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'pageSize' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder clearPageSize() {
      pageSize = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'pageToken' field */
    public java.lang.String getPageToken() {
      return pageToken;
    }
    
    /** Sets the value of the 'pageToken' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder setPageToken(java.lang.String value) {
      validate(fields()[6], value);
      this.pageToken = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'pageToken' field has been set */
    public boolean hasPageToken() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'pageToken' field */
    public org.ga4gh.methods.SearchVariantsRequest.Builder clearPageToken() {
      pageToken = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    public SearchVariantsRequest build() {
      try {
        SearchVariantsRequest record = new SearchVariantsRequest();
        record.variantSetId = fieldSetFlags()[0] ? this.variantSetId : (java.lang.String) defaultValue(fields()[0]);
        record.callSetIds = fieldSetFlags()[1] ? this.callSetIds : (java.util.List<java.lang.String>) defaultValue(fields()[1]);
        record.referenceName = fieldSetFlags()[2] ? this.referenceName : (java.lang.String) defaultValue(fields()[2]);
        record.start = fieldSetFlags()[3] ? this.start : (java.lang.Long) defaultValue(fields()[3]);
        record.end = fieldSetFlags()[4] ? this.end : (java.lang.Long) defaultValue(fields()[4]);
        record.pageSize = fieldSetFlags()[5] ? this.pageSize : (java.lang.Integer) defaultValue(fields()[5]);
        record.pageToken = fieldSetFlags()[6] ? this.pageToken : (java.lang.String) defaultValue(fields()[6]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
