/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.ga4gh.methods;  
@SuppressWarnings("all")
/** This request maps to the body of `POST /readgroupsets/search` as JSON.

TODO: Factor this out to a common API patterns section.
- If searching by a resource ID, and that resource is not found, the method
will return a `404` HTTP status code (`NOT_FOUND`).
- If searching by other attributes, e.g. `name`, and no matches are found, the
method will return a `200` HTTP status code (`OK`) with an empty result list. */
@org.apache.avro.specific.AvroGenerated
public class SearchReadGroupSetsRequest extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SearchReadGroupSetsRequest\",\"namespace\":\"org.ga4gh.methods\",\"doc\":\"This request maps to the body of `POST /readgroupsets/search` as JSON.\\n\\nTODO: Factor this out to a common API patterns section.\\n- If searching by a resource ID, and that resource is not found, the method\\nwill return a `404` HTTP status code (`NOT_FOUND`).\\n- If searching by other attributes, e.g. `name`, and no matches are found, the\\nmethod will return a `200` HTTP status code (`OK`) with an empty result list.\",\"fields\":[{\"name\":\"datasetId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"The dataset to search.\"},{\"name\":\"name\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Only return read group sets with this name (case-sensitive, exact match).\",\"default\":null},{\"name\":\"pageSize\",\"type\":[\"null\",\"int\"],\"doc\":\"Specifies the maximum number of results to return in a single page.\\n  If unspecified, a system default will be used.\",\"default\":null},{\"name\":\"pageToken\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"The continuation token, which is used to page through large result sets.\\n  To get the next page of results, set this parameter to the value of\\n  `nextPageToken` from the previous response.\",\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** The dataset to search. */
   private java.lang.String datasetId;
  /** Only return read group sets with this name (case-sensitive, exact match). */
   private java.lang.String name;
  /** Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used. */
   private java.lang.Integer pageSize;
  /** The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response. */
   private java.lang.String pageToken;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public SearchReadGroupSetsRequest() {}

  /**
   * All-args constructor.
   */
  public SearchReadGroupSetsRequest(java.lang.String datasetId, java.lang.String name, java.lang.Integer pageSize, java.lang.String pageToken) {
    this.datasetId = datasetId;
    this.name = name;
    this.pageSize = pageSize;
    this.pageToken = pageToken;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return datasetId;
    case 1: return name;
    case 2: return pageSize;
    case 3: return pageToken;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: datasetId = (java.lang.String)value$; break;
    case 1: name = (java.lang.String)value$; break;
    case 2: pageSize = (java.lang.Integer)value$; break;
    case 3: pageToken = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'datasetId' field.
   * The dataset to search.   */
  public java.lang.String getDatasetId() {
    return datasetId;
  }

  /**
   * Sets the value of the 'datasetId' field.
   * The dataset to search.   * @param value the value to set.
   */
  public void setDatasetId(java.lang.String value) {
    this.datasetId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * Only return read group sets with this name (case-sensitive, exact match).   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * Only return read group sets with this name (case-sensitive, exact match).   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'pageSize' field.
   * Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used.   */
  public java.lang.Integer getPageSize() {
    return pageSize;
  }

  /**
   * Sets the value of the 'pageSize' field.
   * Specifies the maximum number of results to return in a single page.
  If unspecified, a system default will be used.   * @param value the value to set.
   */
  public void setPageSize(java.lang.Integer value) {
    this.pageSize = value;
  }

  /**
   * Gets the value of the 'pageToken' field.
   * The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response.   */
  public java.lang.String getPageToken() {
    return pageToken;
  }

  /**
   * Sets the value of the 'pageToken' field.
   * The continuation token, which is used to page through large result sets.
  To get the next page of results, set this parameter to the value of
  `nextPageToken` from the previous response.   * @param value the value to set.
   */
  public void setPageToken(java.lang.String value) {
    this.pageToken = value;
  }

  /** Creates a new SearchReadGroupSetsRequest RecordBuilder */
  public static org.ga4gh.methods.SearchReadGroupSetsRequest.Builder newBuilder() {
    return new org.ga4gh.methods.SearchReadGroupSetsRequest.Builder();
  }
  
  /** Creates a new SearchReadGroupSetsRequest RecordBuilder by copying an existing Builder */
  public static org.ga4gh.methods.SearchReadGroupSetsRequest.Builder newBuilder(org.ga4gh.methods.SearchReadGroupSetsRequest.Builder other) {
    return new org.ga4gh.methods.SearchReadGroupSetsRequest.Builder(other);
  }
  
  /** Creates a new SearchReadGroupSetsRequest RecordBuilder by copying an existing SearchReadGroupSetsRequest instance */
  public static org.ga4gh.methods.SearchReadGroupSetsRequest.Builder newBuilder(org.ga4gh.methods.SearchReadGroupSetsRequest other) {
    return new org.ga4gh.methods.SearchReadGroupSetsRequest.Builder(other);
  }
  
  /**
   * RecordBuilder for SearchReadGroupSetsRequest instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SearchReadGroupSetsRequest>
    implements org.apache.avro.data.RecordBuilder<SearchReadGroupSetsRequest> {

    private java.lang.String datasetId;
    private java.lang.String name;
    private java.lang.Integer pageSize;
    private java.lang.String pageToken;

    /** Creates a new Builder */
    private Builder() {
      super(org.ga4gh.methods.SearchReadGroupSetsRequest.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.ga4gh.methods.SearchReadGroupSetsRequest.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.datasetId)) {
        this.datasetId = data().deepCopy(fields()[0].schema(), other.datasetId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.pageSize)) {
        this.pageSize = data().deepCopy(fields()[2].schema(), other.pageSize);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pageToken)) {
        this.pageToken = data().deepCopy(fields()[3].schema(), other.pageToken);
        fieldSetFlags()[3] = true;
      }
    }
    
    /** Creates a Builder by copying an existing SearchReadGroupSetsRequest instance */
    private Builder(org.ga4gh.methods.SearchReadGroupSetsRequest other) {
            super(org.ga4gh.methods.SearchReadGroupSetsRequest.SCHEMA$);
      if (isValidValue(fields()[0], other.datasetId)) {
        this.datasetId = data().deepCopy(fields()[0].schema(), other.datasetId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.pageSize)) {
        this.pageSize = data().deepCopy(fields()[2].schema(), other.pageSize);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.pageToken)) {
        this.pageToken = data().deepCopy(fields()[3].schema(), other.pageToken);
        fieldSetFlags()[3] = true;
      }
    }

    /** Gets the value of the 'datasetId' field */
    public java.lang.String getDatasetId() {
      return datasetId;
    }
    
    /** Sets the value of the 'datasetId' field */
    public org.ga4gh.methods.SearchReadGroupSetsRequest.Builder setDatasetId(java.lang.String value) {
      validate(fields()[0], value);
      this.datasetId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'datasetId' field has been set */
    public boolean hasDatasetId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'datasetId' field */
    public org.ga4gh.methods.SearchReadGroupSetsRequest.Builder clearDatasetId() {
      datasetId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'name' field */
    public java.lang.String getName() {
      return name;
    }
    
    /** Sets the value of the 'name' field */
    public org.ga4gh.methods.SearchReadGroupSetsRequest.Builder setName(java.lang.String value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'name' field has been set */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'name' field */
    public org.ga4gh.methods.SearchReadGroupSetsRequest.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'pageSize' field */
    public java.lang.Integer getPageSize() {
      return pageSize;
    }
    
    /** Sets the value of the 'pageSize' field */
    public org.ga4gh.methods.SearchReadGroupSetsRequest.Builder setPageSize(java.lang.Integer value) {
      validate(fields()[2], value);
      this.pageSize = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'pageSize' field has been set */
    public boolean hasPageSize() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'pageSize' field */
    public org.ga4gh.methods.SearchReadGroupSetsRequest.Builder clearPageSize() {
      pageSize = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'pageToken' field */
    public java.lang.String getPageToken() {
      return pageToken;
    }
    
    /** Sets the value of the 'pageToken' field */
    public org.ga4gh.methods.SearchReadGroupSetsRequest.Builder setPageToken(java.lang.String value) {
      validate(fields()[3], value);
      this.pageToken = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'pageToken' field has been set */
    public boolean hasPageToken() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'pageToken' field */
    public org.ga4gh.methods.SearchReadGroupSetsRequest.Builder clearPageToken() {
      pageToken = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    public SearchReadGroupSetsRequest build() {
      try {
        SearchReadGroupSetsRequest record = new SearchReadGroupSetsRequest();
        record.datasetId = fieldSetFlags()[0] ? this.datasetId : (java.lang.String) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.String) defaultValue(fields()[1]);
        record.pageSize = fieldSetFlags()[2] ? this.pageSize : (java.lang.Integer) defaultValue(fields()[2]);
        record.pageToken = fieldSetFlags()[3] ? this.pageToken : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
